security:
  oauth2:
    client:
      clientId: 67675453421-7h3mj2sd9o1kgrcikkinvm1aghbat1a5.apps.googleusercontent.com
      clientSecret: tYPXOMH_M4wLpqP2Ophu4fm6
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
        - profile
        - email
        - openid
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: false